### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by netgfx** [johnsonjo4531/react-fast-masonry#2]
Is it possible to view the source code of the storybook examples? Or some other example source code?

**Comment by johnsonjo4531** [comment]
Yeah you have to click to show addons on the storybook. On mobile to show addons it’s part of the sidebar and the three dots menu. On desktop the sidebar should be present on the left side with the three dots menu on top. Feel free to ask me any questions here, but I’ll be on vacation the next week or so. Sent from my iPhoneOn Apr 3, 2023, at 1:20 AM, Michael Dobekidis ***@***.***> wrote:﻿
Is it possible to view the source code of the storybook examples? Or some other example source code?

**Comment by netgfx** [comment]
thanks!
